locale                   : "pt-BR"
title                    : "Glass Frog"
title_separator          : " "
subtitle                 : "Data Science Projects"
name                     : "Francisco Piccolo"
description              : "Data Science Portfolio"

# Site Author
author:
  name             : "Francisco Piccolo"
  avatar           : "/assets/images/profile_image.png"
  bio              : "If you can't explain it simply, you don't understand it well enough"
  location         : "Jundiaí-SP"
  email            :
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FranciscoPicco1"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/franciscopiccolo/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FranciscoPiccolo"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
