baseurl = "/"
title   = "Glass Frog"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Francisco Piccolo"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]

  homeSubtitle = "Statistics Review"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "Home"
    logoHomeLink = "/"

# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/FranciscoPicco1"

  [[params.social]]
    name = "email"
    url  = "tobias.piccolo@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/FranciscoPiccolo"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/franciscopiccolo/"

[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "book_review"
    name       = "Book Review"
    url        = "books/"
  [[menu.main]]
    identifier = "brokerage"
    name       = "Brokerage"
    url        = "brokerage/"


